#!/bin/bash

trap : INT

if [ "$1" != "c++" ] && [ "$1" != "python" ]; then
  echo "Linguaggio sconosciuto: $1"
  exit 2
fi

if [ -f input.txt ]; then
  echo "input.txt già esistente!"
  echo "Eseguire il programma direttamente per testare solo quell'input,"
  echo "oppure rinominare input.txt per poter eseguire il test completo."
  exit 3
fi

for input in *input*.txt; do
  echo "$input:"
  mv $input input.txt

  if [ "$1" = "c++" ]; then ./main
  else python main.py; fi
  code=$?

  mv input.txt $input

  if [ $code -ne 0 ]; then
    echo "Il programma ha terminato con il codice di uscita $code"
    exit 1
  fi

  output=${input/input/output}
  if ! diff output.txt $output > /dev/null; then
    echo "L'output non è corretto:"
    hw=$(((COLUMNS - 10) / 2))
    hwl=$(((hw - 10) / 2))
    hwr=$(((hw - ${#output}) / 2))
    printf "%*soutput.txt%*s | %*s%s\n" $hwl "" $((hwl + hw % 2)) "" $hwr "" $output
    printf "%.0s-" $(seq 0 $hw); printf "+"; printf "%.0s-" $(seq $hw); echo
    diff -yW$COLUMNS --color output.txt $output
    exit 1
  fi

  echo "L'output è corretto"
done

rm output.txt
